version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-ubicua
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    networks:
      - red-ubicua

  database:
    image: mariadb:latest
    container_name: db-ubicua
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ubicua_db
      MARIADB_ROOT_PASSWORD: admin
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - red-ubicua

  tomcat-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tomcat-ubicua
    ports:
      - "8081:8080"
    restart: unless-stopped
    volumes:
      - ./tomcat-logs:/usr/local/tomcat/logs
    depends_on:
      - database
      - mqtt-broker
    networks:
      - red-ubicua

networks:
  red-ubicua:
    driver: bridge